### PR TITLE
Configured leader election to use configmaps

### PR DESCRIPTION
**Pull request by sabre1041**
Configured leader election to use ConfigMaps

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Can you elaborate a bit on why this is preferred? Wouldn't also the RBAC need to be changed for that?

**Comment by sabre1041** [comment]
The SA does not have rights by default to the resources due to changes in recent Kubernetes versions. RBAC already does have this type of configuration setup

https://github.com/evryfs/github-actions-runner-operator/blob/master/config/rbac/leader_election_role.yaml#L9

**Comment by davidkarlsen** [comment]
@sabre1041 see comment in controller runtime. It seems it is legacy to use configmaps for election?

**Comment by sabre1041** [comment]
We need to be able to support older Kubernetes environments.

**Comment by sabre1041** [comment]
1.18 i believe

**Comment by davidkarlsen** [comment]
Seems to exist in 1.16 too: https://v1-16.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#lease-v1beta1-coordination-k8s-io

**Comment by sabre1041** [comment]
@davidkarlsen can we move forward on this.

**Review by davidkarlsen — APPROVED** [review]

**Comment by BastianM3** [comment]
Just tried installing on 1.16 and seem to be tripping over this error :/ Is there a good workaround for this?

```
E0304 04:24:39.197395       1 leaderelection.go:325] error retrieving resource lock github-actions-runner-operator/4ef9cd91.tietoevry.com: configmaps "4ef9cd91.tietoevry.com" is forbidden: User "system:serviceaccount:github-actions-runner-operator:github-actions-operator" cannot get resource "configmaps" in API group "" in the namespace "github-actions-runner-operator"
```

**Comment by davidkarlsen** [comment]
@BastianM3 it should be covered by the existing role: https://github.com/evryfs/helm-charts/blob/master/charts/github-actions-runner-operator/templates/role.yaml#L18.

How did you install garo? Can you double-check the role?

**Pull request merged**
